"""Train lightweight device-level GNSS spoofing alarm baselines."""

from __future__ import annotations

import argparse
import json
import logging
import random
import sys
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from torch import nn
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from models import (
    DeviceStatsDLinear,
    DeviceStatsDepthwiseCNN,
    DeviceStatsGRU,
    DeviceStatsLSTM,
    DeviceStatsMLP,
    DeviceStatsNLinear,
    DeviceStatsTCN,
)


logging.basicConfig(level=logging.INFO, format="%(asctime)s - [%(levelname)s] - %(message)s")
LOGGER = logging.getLogger(__name__)


class DeviceWindowDataset(Dataset):
    """One causal statistics window and one device alarm label per item."""

    def __init__(self, npz_path: Path):
        with np.load(npz_path) as data:
            self.x = torch.from_numpy(data["x"]).float()
            self.y = torch.from_numpy(data["y"]).long()
        if self.x.ndim != 3 or self.y.ndim != 1 or len(self.x) != len(self.y):
            raise ValueError(f"Invalid device tensor shapes in {npz_path}: x={self.x.shape}, y={self.y.shape}")

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, index: int):
        return self.x[index], self.y[index]


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


def class_weights(dataset: DeviceWindowDataset) -> torch.Tensor | None:
    counts = torch.bincount(dataset.y, minlength=2).float()
    if torch.any(counts == 0):
        return None
    return counts.sum() / (2.0 * counts)


def build_model(name: str, input_dim: int, time_steps: int, hidden_dim: int, dropout: float) -> nn.Module:
    if name == "device_stats_mlp":
        return DeviceStatsMLP(input_dim=input_dim, time_steps=time_steps, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_gru":
        return DeviceStatsGRU(input_dim=input_dim, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_lstm":
        return DeviceStatsLSTM(input_dim=input_dim, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_tcn":
        return DeviceStatsTCN(input_dim=input_dim, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_depthwise_cnn":
        return DeviceStatsDepthwiseCNN(input_dim=input_dim, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_nlinear":
        return DeviceStatsNLinear(input_dim=input_dim, time_steps=time_steps, hidden_dim=hidden_dim, dropout=dropout)
    if name == "device_stats_dlinear":
        return DeviceStatsDLinear(input_dim=input_dim, time_steps=time_steps, hidden_dim=hidden_dim, dropout=dropout)
    raise ValueError(f"Unknown model: {name}")


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, criterion: nn.Module, device: torch.device) -> dict[str, float | int]:
    model.eval()
    losses: list[float] = []
    predictions: list[np.ndarray] = []
    targets: list[np.ndarray] = []
    for x, y in loader:
        logits = model(x.to(device))
        y = y.to(device)
        losses.append(float(criterion(logits, y).item()) * len(y))
        predictions.append(logits.argmax(dim=-1).cpu().numpy())
        targets.append(y.cpu().numpy())
    if not targets:
        return {"loss": float("nan"), "macro_f1": 0.0, "precision": 0.0, "recall": 0.0, "far": 0.0, "samples": 0}
    y_true = np.concatenate(targets)
    y_pred = np.concatenate(predictions)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return {
        "loss": float(sum(losses) / len(y_true)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "far": float(fp / (fp + tn)) if fp + tn else 0.0,
        "samples": int(len(y_true)),
        "true_negative": int(tn),
        "false_positive": int(fp),
        "false_negative": int(fn),
        "true_positive": int(tp),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True, help="Directory generated by step 13.")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--model",
        choices=[
            "device_stats_mlp",
            "device_stats_gru",
            "device_stats_lstm",
            "device_stats_tcn",
            "device_stats_depthwise_cnn",
            "device_stats_nlinear",
            "device_stats_dlinear",
        ],
        default="device_stats_gru",
    )
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--hidden-dim", type=int, default=24)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--patience", type=int, default=6)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--test-only", action="store_true")
    parser.add_argument("--checkpoint", type=Path, default=None)
    args = parser.parse_args()
    if args.test_only and args.dry_run:
        parser.error("--test-only cannot be combined with --dry-run")

    set_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    train_path = args.data_dir / "train.npz"
    val_path = args.data_dir / "val.npz"
    for path in (train_path, val_path):
        if not path.exists():
            raise FileNotFoundError(path)
    train_data = DeviceWindowDataset(train_path)
    val_data = DeviceWindowDataset(val_path)
    input_dim = int(train_data.x.shape[-1])
    time_steps = int(train_data.x.shape[-2])
    if tuple(val_data.x.shape[-2:]) != (time_steps, input_dim):
        raise ValueError("Train and validation device tensors use different dimensions.")
    model = build_model(args.model, input_dim, time_steps, args.hidden_dim, args.dropout).to(device)
    parameter_count = sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad)
    LOGGER.info("Model=%s device=%s parameters=%d input=[device, %d, %d]", args.model, device, parameter_count, time_steps, input_dim)

    pin_memory = device.type == "cuda"
    train_loader = DataLoader(train_data, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers, pin_memory=pin_memory)
    val_loader = DataLoader(val_data, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, pin_memory=pin_memory)
    if args.dry_run:
        x, _ = next(iter(train_loader))
        with torch.no_grad():
            logits = model(x.to(device))
        LOGGER.info("Dry run passed: logits=%s; no weights updated and no test data read.", tuple(logits.shape))
        return

    args.output_dir.mkdir(parents=True, exist_ok=True)
    weights = class_weights(train_data)
    criterion = nn.CrossEntropyLoss(weight=weights.to(device) if weights is not None else None)
    checkpoint_path = args.checkpoint or args.output_dir / f"best_{args.model}.pt"
    if args.test_only:
        if not checkpoint_path.exists():
            raise FileNotFoundError(checkpoint_path)
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
        if checkpoint.get("model") != args.model:
            raise ValueError(f"Checkpoint model is {checkpoint.get('model')}, not {args.model}")
        model = build_model(
            checkpoint["model"], int(checkpoint["input_dim"]), int(checkpoint["time_steps"]),
            int(checkpoint["hidden_dim"]), float(checkpoint["dropout"]),
        ).to(device)
        model.load_state_dict(checkpoint["state_dict"])
        test_path = args.data_dir / "test.npz"
        if not test_path.exists():
            raise FileNotFoundError(test_path)
        test_loader = DataLoader(DeviceWindowDataset(test_path), batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, pin_memory=pin_memory)
        metrics = evaluate(model, test_loader, criterion, device)
        (args.output_dir / f"test_metrics_{args.model}.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
        LOGGER.info("Test-only metrics=%s", json.dumps(metrics, ensure_ascii=False))
        return

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    best_f1 = -1.0
    stale_epochs = 0
    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        total_samples = 0
        for x, y in tqdm(train_loader, desc=f"Epoch {epoch}/{args.epochs}"):
            logits = model(x.to(device))
            y = y.to(device)
            loss = criterion(logits, y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += float(loss.item()) * len(y)
            total_samples += len(y)
        val_metrics = evaluate(model, val_loader, criterion, device)
        LOGGER.info("Epoch %d: train_loss=%.4f val=%s", epoch, total_loss / max(total_samples, 1), json.dumps(val_metrics, ensure_ascii=False))
        if val_metrics["macro_f1"] > best_f1:
            best_f1 = float(val_metrics["macro_f1"])
            stale_epochs = 0
            checkpoint = {
                "model": args.model,
                "input_dim": input_dim,
                "time_steps": time_steps,
                "hidden_dim": args.hidden_dim,
                "dropout": args.dropout,
                "state_dict": model.state_dict(),
                "val_metrics": val_metrics,
            }
            torch.save(checkpoint, checkpoint_path)
            (args.output_dir / f"val_metrics_{args.model}.json").write_text(json.dumps(val_metrics, indent=2), encoding="utf-8")
        else:
            stale_epochs += 1
            if stale_epochs >= args.patience:
                LOGGER.info("Early stopping after %d epochs without validation macro-F1 improvement.", args.patience)
                break
    LOGGER.info("Training complete. Test data was not read; use --test-only only after locking this device baseline.")


if __name__ == "__main__":
    main()
