"""Train a small device-window attack-event baseline.

The tensors are generated by 36_build_device_attack_event_tensors.py.  Train
and validation are used for model selection; an outer test can be read only by
an explicit --test-only run after checkpoint selection.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any

import numpy as np
import torch
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_recall_fscore_support, precision_score, recall_score
from torch import nn
from torch.utils.data import DataLoader, Dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--model", choices=("linear", "mlp"), default="linear")
    parser.add_argument(
        "--label-key",
        choices=(
            "y_event", "y_response_state",
            "y_associated_anomaly_l1", "y_associated_anomaly_l5",
            "y_direct_l1", "y_direct_l5",
        ),
        default="y_event",
        help="tensor label; band-specific labels are independent binary targets and do not use legacy state transforms",
    )
    parser.add_argument(
        "--label-transform", choices=("raw", "abnormal", "anomaly_only", "response_type", "direct"), default="raw",
        help="raw keeps the selected label; abnormal maps response states 1/2 to one; anomaly_only maps anomaly to one and excludes direct rows; response_type keeps states 1/2 and maps anomaly/direct to 0/1; direct maps state 2 to one",
    )
    parser.add_argument(
        "--sample-scope", choices=("all", "associated_l1", "associated_l5"), default="all",
        help="associated_* keeps attack-active, baseline-capable, non-target windows; current band loss remains eligible evidence",
    )
    parser.add_argument("--num-classes", type=int, default=0, help="override class count; inferred from train/val when omitted")
    parser.add_argument("--hidden-dim", type=int, default=16)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-3)
    parser.add_argument("--patience", type=int, default=8)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--include-devices", nargs="+", help="restrict training/evaluation to named receiver devices")
    parser.add_argument(
        "--include-scenarios", nargs="+",
        help="restrict training/evaluation to named recording scenarios (for example st_L5)",
    )
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--test-only", action="store_true")
    parser.add_argument("--calibrate-only", action="store_true", help="select an alarm threshold on val.npz using an existing checkpoint")
    parser.add_argument(
        "--calibration-data-dir", type=Path,
        help="optional tensor directory whose val.npz is used for threshold calibration; defaults to --data-dir",
    )
    parser.add_argument("--thresholds", type=float, nargs="+", default=[0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95])
    parser.add_argument("--max-val-far", type=float, default=0.10)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if min(args.hidden_dim, args.epochs, args.batch_size, args.patience) < 1 or args.num_workers < 0:
        parser.error("training dimensions and counts must be positive")
    if args.num_classes < 0:
        parser.error("num-classes must be non-negative")
    if not 0.0 <= args.dropout < 1.0:
        parser.error("dropout must be in [0, 1)")
    if (args.test_only or args.calibrate_only) and args.checkpoint is None:
        parser.error("--test-only and --calibrate-only require --checkpoint")
    if args.test_only and args.calibrate_only:
        parser.error("--test-only and --calibrate-only are mutually exclusive")
    if any(not 0.0 < value < 1.0 for value in args.thresholds):
        parser.error("thresholds must be strictly between zero and one")
    if not 0.0 <= args.max_val_far <= 1.0:
        parser.error("max-val-far must be in [0, 1]")
    expected_label = {
        "associated_l1": "y_associated_anomaly_l1",
        "associated_l5": "y_associated_anomaly_l5",
    }.get(args.sample_scope)
    if expected_label is not None and args.label_key != expected_label:
        parser.error(f"--sample-scope {args.sample_scope} requires --label-key {expected_label}")
    if args.sample_scope != "all" and args.label_transform != "raw":
        parser.error("Scene-conditioned associated-anomaly labels are already binary; use --label-transform raw")
    return args


def seed_all(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


class EventDataset(Dataset):
    REQUIRED = {"x", "device_id", "recording_id", "source_id", "endpoint_tow"}

    def __init__(
        self,
        path: Path,
        label_key: str,
        include_device_ids: set[int] | None = None,
        label_transform: str = "raw",
        include_recording_ids: set[int] | None = None,
        sample_scope: str = "all",
    ) -> None:
        with np.load(path, allow_pickle=False) as data:
            required = self.REQUIRED.union({label_key})
            scope_keys = {
                "associated_l1": {"y_event", "baseline_has_l1", "y_target_l1"},
                "associated_l5": {"y_event", "baseline_has_l5", "y_target_l5"},
            }
            required.update(scope_keys.get(sample_scope, set()))
            if missing := required.difference(data.files):
                raise ValueError(f"{path} is missing {sorted(missing)}")
            self.x = torch.from_numpy(data["x"].astype(np.float32))
            labels = data[label_key].astype(np.int64)
            self.device_id = torch.from_numpy(data["device_id"].astype(np.int64))
            self.recording_id = torch.from_numpy(data["recording_id"].astype(np.int64))
            self.source_id = torch.from_numpy(data["source_id"].astype(np.int64))
            self.endpoint_tow = torch.from_numpy(data["endpoint_tow"].astype(np.float64))
            if sample_scope == "associated_l1":
                scope_selected = (data["y_event"] == 1) & (data["baseline_has_l1"] == 1) & (data["y_target_l1"] == 0)
            elif sample_scope == "associated_l5":
                scope_selected = (data["y_event"] == 1) & (data["baseline_has_l5"] == 1) & (data["y_target_l5"] == 0)
            elif sample_scope == "all":
                scope_selected = np.ones(len(labels), dtype=bool)
            else:
                raise ValueError(f"Unsupported sample scope: {sample_scope}")
        if label_transform == "abnormal":
            labels = (labels > 0).astype(np.int64)
        elif label_transform == "anomaly_only":
            # A single-frequency receiver should learn its indirect response
            # separately from direct spoof labels.  Direct rows are not
            # negatives for this task and are removed below via the -1 mask.
            labels = np.where(labels == 2, -1, (labels == 1).astype(np.int64))
        elif label_transform == "response_type":
            labels = np.where(labels > 0, labels - 1, -1).astype(np.int64)
        elif label_transform == "direct":
            labels = (labels == 2).astype(np.int64)
        elif label_transform != "raw":
            raise ValueError(f"Unsupported label transform: {label_transform}")
        self.y = torch.from_numpy(labels)
        if include_device_ids is not None or include_recording_ids is not None or sample_scope != "all":
            selected = torch.from_numpy(scope_selected.astype(bool))
        if include_device_ids is not None:
            device_selected = torch.zeros(len(self.device_id), dtype=torch.bool)
            for device_id in include_device_ids:
                device_selected |= self.device_id == device_id
            selected &= device_selected
        if include_recording_ids is not None:
            recording_selected = torch.zeros(len(self.recording_id), dtype=torch.bool)
            for recording_id in include_recording_ids:
                recording_selected |= self.recording_id == recording_id
            selected &= recording_selected
        if include_device_ids is not None or include_recording_ids is not None or sample_scope != "all":
            self.x = self.x[selected]
            self.y = self.y[selected]
            self.device_id = self.device_id[selected]
            self.recording_id = self.recording_id[selected]
            self.source_id = self.source_id[selected]
            self.endpoint_tow = self.endpoint_tow[selected]
        valid = self.y >= 0
        if not torch.all(valid):
            self.x = self.x[valid]
            self.y = self.y[valid]
            self.device_id = self.device_id[valid]
            self.recording_id = self.recording_id[valid]
            self.source_id = self.source_id[valid]
            self.endpoint_tow = self.endpoint_tow[valid]
        if self.x.ndim != 2 or len(self.x) != len(self.y):
            raise ValueError(f"Invalid device tensor shapes in {path}")

    def __len__(self) -> int:
        return len(self.y)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.x[index], self.y[index]


class EventMLP(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, dropout: float, num_classes: int) -> None:
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), nn.GELU(), nn.Dropout(dropout), nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.layers(x)


def make_model(kind: str, input_dim: int, hidden_dim: int, dropout: float, num_classes: int) -> nn.Module:
    return nn.Linear(input_dim, num_classes) if kind == "linear" else EventMLP(input_dim, hidden_dim, dropout, num_classes)


def binary_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float | int]:
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return {
        "samples": int(len(y_true)), "negative_support": int((y_true == 0).sum()), "positive_support": int((y_true == 1).sum()),
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "far": float(fp / (fp + tn)) if fp + tn else 0.0,
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
    }


def multiclass_metrics(y_true: np.ndarray, y_pred: np.ndarray, num_classes: int) -> dict[str, Any]:
    labels = list(range(num_classes))
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true, y_pred, labels=labels, zero_division=0,
    )
    normal = y_true == 0
    abnormal = y_true != 0
    false_alarm = normal & (y_pred != 0)
    result: dict[str, Any] = {
        "samples": int(len(y_true)),
        "accuracy": float(accuracy_score(y_true, y_pred)) if len(y_true) else 0.0,
        "macro_f1": float(f1_score(y_true, y_pred, labels=labels, average="macro", zero_division=0)),
        "supported_macro_f1": float(np.mean(f1[support > 0])) if np.any(support > 0) else 0.0,
        "far": float(false_alarm.sum() / normal.sum()) if normal.sum() else 0.0,
        "abnormal_recall": float(((y_pred != 0) & abnormal).sum() / abnormal.sum()) if abnormal.sum() else 0.0,
        "recall": float(((y_pred != 0) & abnormal).sum() / abnormal.sum()) if abnormal.sum() else 0.0,
        "confusion_matrix": confusion_matrix(y_true, y_pred, labels=labels).astype(int).tolist(),
        "per_class": {},
    }
    for class_id in labels:
        result["per_class"][str(class_id)] = {
            "support": int(support[class_id]),
            "precision": float(precision[class_id]),
            "recall": float(recall[class_id]),
            "f1": float(f1[class_id]),
        }
    if num_classes == 2:
        result.update(binary_metrics(y_true, y_pred))
    return result


def infer_num_classes(*datasets: EventDataset, requested: int = 0) -> int:
    if requested:
        return requested
    maxima = [int(data.y.max()) for data in datasets if len(data)]
    if not maxima:
        raise ValueError("Cannot infer class count from empty datasets")
    return max(maxima) + 1


@torch.no_grad()
def probabilities(model: nn.Module, data: EventDataset, device: torch.device, batch_size: int) -> np.ndarray:
    model.eval()
    batches = [model(data.x[start:start + batch_size].to(device)).cpu() for start in range(0, len(data), batch_size)]
    return torch.cat(batches).softmax(dim=1).numpy() if batches else np.empty((0, 0), dtype=np.float64)


def group_metrics(
    labels: np.ndarray,
    predicted: np.ndarray,
    keys: np.ndarray,
    names: dict[int, str] | None,
    num_classes: int,
) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for key in np.unique(keys):
        selected = keys == key
        name = names.get(int(key), str(int(key))) if names is not None else str(key)
        result[name] = multiclass_metrics(labels[selected], predicted[selected], num_classes)
    return result


def recording_names(metadata: dict[str, Any]) -> dict[int, str]:
    rows = metadata.get("recordings", [])
    if not isinstance(rows, list):
        return {}
    result: dict[int, str] = {}
    for recording_id, row in enumerate(rows):
        if isinstance(row, dict):
            result[recording_id] = "/".join(str(row.get(key, "")) for key in ("Environment", "Scenario", "Session"))
    return result


def scenario_ids(metadata: dict[str, Any], recording_ids: np.ndarray) -> tuple[np.ndarray, dict[int, str]]:
    rows = metadata.get("recordings", [])
    scenario_to_id: dict[str, int] = {}
    names: dict[int, str] = {}
    mapped = np.zeros(len(recording_ids), dtype=np.int64)
    for index, recording_id in enumerate(recording_ids.astype(np.int64)):
        scenario = "unknown"
        if isinstance(rows, list) and 0 <= int(recording_id) < len(rows) and isinstance(rows[int(recording_id)], dict):
            scenario = str(rows[int(recording_id)].get("Scenario", "unknown"))
        if scenario not in scenario_to_id:
            scenario_to_id[scenario] = len(scenario_to_id)
            names[scenario_to_id[scenario]] = scenario
        mapped[index] = scenario_to_id[scenario]
    return mapped, names


def evaluate_probability(
    data: EventDataset,
    probability: np.ndarray,
    threshold: float | None,
    device_names: dict[int, str],
    num_classes: int,
    metadata: dict[str, Any],
) -> dict[str, Any]:
    if len(probability) != len(data):
        raise ValueError("Probability count differs from event windows")
    if probability.ndim != 2 or probability.shape[1] != num_classes:
        raise ValueError("Probability tensor shape differs from class count")
    if num_classes == 2 and threshold is not None:
        predicted = (probability[:, 1] >= threshold).astype(np.int64)
    else:
        predicted = probability.argmax(axis=1).astype(np.int64)
    labels = data.y.numpy()
    result: dict[str, Any] = {"alarm_threshold": threshold, "overall": multiclass_metrics(labels, predicted, num_classes)}
    device_ids = data.device_id.numpy()
    recording_ids = data.recording_id.numpy()
    scenario_key, scenario_names = scenario_ids(metadata, recording_ids)
    result["by_device"] = group_metrics(labels, predicted, device_ids, device_names, num_classes)
    result["by_scenario"] = group_metrics(labels, predicted, scenario_key, scenario_names, num_classes)
    result["by_recording"] = group_metrics(labels, predicted, recording_ids, recording_names(metadata), num_classes)
    return result


def evaluate(model: nn.Module, data: EventDataset, device: torch.device, batch_size: int, device_names: dict[int, str], num_classes: int, metadata: dict[str, Any]) -> dict[str, Any]:
    threshold = 0.5 if num_classes == 2 else None
    return evaluate_probability(data, probabilities(model, data, device, batch_size), threshold, device_names, num_classes, metadata)


def load_checkpoint_model(checkpoint_path: Path, device: torch.device, input_dim: int) -> tuple[dict[str, Any], nn.Module]:
    try:
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    except TypeError:
        checkpoint = torch.load(checkpoint_path, map_location=device)
    required = {"model", "input_dim", "hidden_dim", "dropout", "state_dict"}
    if missing := required.difference(checkpoint):
        raise ValueError(f"Invalid checkpoint; missing {sorted(missing)}")
    if input_dim != int(checkpoint["input_dim"]):
        raise ValueError("Checkpoint and tensor feature dimensions differ")
    num_classes = int(checkpoint.get("num_classes", 2))
    model = make_model(checkpoint["model"], int(checkpoint["input_dim"]), int(checkpoint["hidden_dim"]), float(checkpoint["dropout"]), num_classes).to(device)
    model.load_state_dict(checkpoint["state_dict"])
    return checkpoint, model


def validate_checkpoint_task_contract(checkpoint: dict[str, Any], args: argparse.Namespace) -> None:
    """Prevent evaluation with a checkpoint trained for a different label task."""
    checkpoint_label = checkpoint.get("label_key")
    checkpoint_transform = checkpoint.get("label_transform")
    checkpoint_scope = checkpoint.get("sample_scope", "all")
    if checkpoint_label is not None and checkpoint_label != args.label_key:
        raise ValueError(
            f"Checkpoint label key {checkpoint_label!r} differs from requested {args.label_key!r}"
        )
    if checkpoint_transform is not None and checkpoint_transform != args.label_transform:
        raise ValueError(
            f"Checkpoint label transform {checkpoint_transform!r} differs from requested {args.label_transform!r}"
        )
    if checkpoint_scope != args.sample_scope:
        raise ValueError(
            f"Checkpoint sample scope {checkpoint_scope!r} differs from requested {args.sample_scope!r}"
        )


def calibrate_checkpoint(
    args: argparse.Namespace,
    device_names: dict[int, str],
    device: torch.device,
    include_device_ids: set[int] | None,
    include_recording_ids: set[int] | None,
) -> None:
    calibration_data_dir = args.calibration_data_dir or args.data_dir
    val = EventDataset(
        calibration_data_dir / "val.npz", args.label_key, include_device_ids, args.label_transform, include_recording_ids,
        args.sample_scope,
    )
    checkpoint, model = load_checkpoint_model(args.checkpoint, device, val.x.shape[1])
    validate_checkpoint_task_contract(checkpoint, args)
    if int(checkpoint.get("num_classes", 2)) != 2:
        raise ValueError("--calibrate-only currently applies only to binary checkpoints")
    negative_support = int((val.y == 0).sum().item())
    positive_support = int((val.y == 1).sum().item())
    if negative_support == 0 or positive_support == 0:
        raise ValueError(
            "Threshold calibration requires both classes in the calibration split; "
            f"split={calibration_data_dir / 'val.npz'} negative_support={negative_support} "
            f"positive_support={positive_support}. Refusing to calibrate on a single-class split."
        )
    probability = probabilities(model, val, device, args.batch_size)
    metadata = json.loads((calibration_data_dir / "metadata.json").read_text(encoding="utf-8"))
    candidates = [evaluate_probability(val, probability, threshold, device_names, 2, metadata) for threshold in args.thresholds]
    eligible = [candidate for candidate in candidates if candidate["overall"]["far"] <= args.max_val_far]
    if eligible:
        selected = max(eligible, key=lambda candidate: (candidate["overall"]["macro_f1"], candidate["overall"]["recall"], -candidate["overall"]["far"]))
    else:
        selected = min(candidates, key=lambda candidate: (candidate["overall"]["far"], -candidate["overall"]["macro_f1"]))
    checkpoint["alarm_threshold"] = float(selected["alarm_threshold"])
    checkpoint["calibration"] = {
        "split": "val",
        "data_dir": str(calibration_data_dir),
        "max_val_far": args.max_val_far,
        "negative_support": negative_support,
        "positive_support": positive_support,
        "calibration_valid": True,
        "metrics": selected,
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    calibrated_path = args.output_dir / f"calibrated_{args.checkpoint.name}"
    torch.save(checkpoint, calibrated_path)
    save_json(args.output_dir / "val_threshold_calibration.json", {
        "split": "val",
        "data_dir": str(calibration_data_dir),
        "max_val_far": args.max_val_far,
        "negative_support": negative_support,
        "positive_support": positive_support,
        "calibration_valid": True,
        "selected": selected,
        "candidates": candidates,
    })
    print(json.dumps({"checkpoint": str(calibrated_path), "selected_threshold": selected["alarm_threshold"], "val_metrics": selected["overall"]}, indent=2))


def class_weights(data: EventDataset, num_classes: int) -> torch.Tensor:
    counts = torch.bincount(data.y, minlength=num_classes).float()
    if torch.any(counts == 0):
        raise ValueError(f"Train split lacks an event class: {counts.tolist()}")
    return counts.sum() / (float(num_classes) * counts)


def save_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2), encoding="utf-8")


def main() -> None:
    args = parse_args()
    seed_all(args.seed)
    metadata = json.loads((args.data_dir / "metadata.json").read_text(encoding="utf-8"))
    device_names = {int(value): str(key) for key, value in metadata.get("device_mapping", {}).items()}
    named_device_ids = {name: device_id for device_id, name in device_names.items()}
    include_device_ids: set[int] | None = None
    if args.include_devices:
        unknown = sorted(set(args.include_devices).difference(named_device_ids))
        if unknown:
            raise ValueError(f"Unknown device names: {unknown}; available={sorted(named_device_ids)}")
        include_device_ids = {named_device_ids[name] for name in args.include_devices}
    include_recording_ids: set[int] | None = None
    if args.include_scenarios:
        recordings = metadata.get("recordings", [])
        if not isinstance(recordings, list):
            raise ValueError("metadata has no recording list")
        available_scenarios = {str(row.get("Scenario", "")) for row in recordings if isinstance(row, dict)}
        unknown_scenarios = sorted(set(args.include_scenarios).difference(available_scenarios))
        if unknown_scenarios:
            raise ValueError(f"Unknown scenarios: {unknown_scenarios}; available={sorted(available_scenarios)}")
        include_recording_ids = {
            recording_id for recording_id, row in enumerate(recordings)
            if isinstance(row, dict) and str(row.get("Scenario", "")) in args.include_scenarios
        }
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if args.test_only:
        test = EventDataset(
            args.data_dir / "test.npz", args.label_key, include_device_ids, args.label_transform, include_recording_ids,
            args.sample_scope,
        )
        checkpoint, model = load_checkpoint_model(args.checkpoint, device, test.x.shape[1])
        validate_checkpoint_task_contract(checkpoint, args)
        args.output_dir.mkdir(parents=True, exist_ok=True)
        num_classes = int(checkpoint.get("num_classes", 2))
        threshold = float(checkpoint.get("alarm_threshold", 0.5)) if num_classes == 2 else None
        save_json(args.output_dir / "test_metrics_device_event.json", evaluate_probability(test, probabilities(model, test, device, args.batch_size), threshold, device_names, num_classes, metadata))
        return
    if args.calibrate_only:
        calibrate_checkpoint(args, device_names, device, include_device_ids, include_recording_ids)
        return

    train = EventDataset(
        args.data_dir / "train.npz", args.label_key, include_device_ids, args.label_transform, include_recording_ids,
        args.sample_scope,
    )
    val = EventDataset(
        args.data_dir / "val.npz", args.label_key, include_device_ids, args.label_transform, include_recording_ids,
        args.sample_scope,
    )
    if len(val) == 0:
        raise ValueError("Validation is empty; use a tensor directory with an inner validation split")
    num_classes = infer_num_classes(train, val, requested=args.num_classes)
    model = make_model(args.model, train.x.shape[1], args.hidden_dim, args.dropout, num_classes).to(device)
    if args.dry_run:
        print(json.dumps({"device": str(device), "model": args.model, "label_key": args.label_key, "num_classes": num_classes, "train_windows": len(train), "val_windows": len(val), "features": int(train.x.shape[1])}))
        return
    criterion = nn.CrossEntropyLoss(weight=class_weights(train, num_classes).to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    loader = DataLoader(train, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers)
    best_score, best_state, stale = float("-inf"), None, 0
    history: list[dict[str, float | int]] = []
    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        for x, y in loader:
            loss = criterion(model(x.to(device)), y.to(device))
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += float(loss.item()) * len(y)
        val_metrics = evaluate(model, val, device, args.batch_size, device_names, num_classes, metadata)["overall"]
        row = {"epoch": epoch, "train_loss": total_loss / len(train), **val_metrics}
        history.append(row)
        score = float(val_metrics["macro_f1"])
        if score > best_score:
            best_score = score
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            stale = 0
        else:
            stale += 1
            if stale >= args.patience:
                break
    if best_state is None:
        raise RuntimeError("No checkpoint selected")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_path = args.output_dir / f"best_device_event_{args.model}.pt"
    torch.save({
        "model": args.model, "input_dim": int(train.x.shape[1]), "hidden_dim": args.hidden_dim, "dropout": args.dropout,
        "best_val_macro_f1": best_score, "state_dict": best_state, "task": "device_attack_event",
        "label_key": args.label_key, "num_classes": num_classes,
        "label_transform": args.label_transform, "sample_scope": args.sample_scope,
        "label_semantics": metadata.get("label_semantics"),
        "included_device_names": args.include_devices, "included_scenarios": args.include_scenarios,
    }, checkpoint_path)
    save_json(args.output_dir / "training_history.json", history)
    model.load_state_dict(best_state)
    save_json(args.output_dir / "val_metrics_device_event.json", evaluate(model, val, device, args.batch_size, device_names, num_classes, metadata))
    print(json.dumps({"checkpoint": str(checkpoint_path), "best_val_macro_f1": best_score, "epochs": len(history)}, indent=2))


if __name__ == "__main__":
    main()
