"""Train a small device-window attack-event baseline.

The tensors are generated by 36_build_device_attack_event_tensors.py.  Train
and validation are used for model selection; an outer test can be read only by
an explicit --test-only run after checkpoint selection.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any

import numpy as np
import torch
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from torch import nn
from torch.utils.data import DataLoader, Dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--model", choices=("linear", "mlp"), default="linear")
    parser.add_argument("--hidden-dim", type=int, default=16)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-3)
    parser.add_argument("--patience", type=int, default=8)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--include-devices", nargs="+", help="restrict training/evaluation to named receiver devices")
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--test-only", action="store_true")
    parser.add_argument("--calibrate-only", action="store_true", help="select an alarm threshold on val.npz using an existing checkpoint")
    parser.add_argument("--thresholds", type=float, nargs="+", default=[0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95])
    parser.add_argument("--max-val-far", type=float, default=0.10)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if min(args.hidden_dim, args.epochs, args.batch_size, args.patience) < 1 or args.num_workers < 0:
        parser.error("training dimensions and counts must be positive")
    if not 0.0 <= args.dropout < 1.0:
        parser.error("dropout must be in [0, 1)")
    if (args.test_only or args.calibrate_only) and args.checkpoint is None:
        parser.error("--test-only and --calibrate-only require --checkpoint")
    if args.test_only and args.calibrate_only:
        parser.error("--test-only and --calibrate-only are mutually exclusive")
    if any(not 0.0 < value < 1.0 for value in args.thresholds):
        parser.error("thresholds must be strictly between zero and one")
    if not 0.0 <= args.max_val_far <= 1.0:
        parser.error("max-val-far must be in [0, 1]")
    return args


def seed_all(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


class EventDataset(Dataset):
    REQUIRED = {"x", "y_event", "device_id", "recording_id", "source_id", "endpoint_tow"}

    def __init__(self, path: Path, include_device_ids: set[int] | None = None) -> None:
        with np.load(path, allow_pickle=False) as data:
            if missing := self.REQUIRED.difference(data.files):
                raise ValueError(f"{path} is missing {sorted(missing)}")
            self.x = torch.from_numpy(data["x"].astype(np.float32))
            self.y = torch.from_numpy(data["y_event"].astype(np.int64))
            self.device_id = torch.from_numpy(data["device_id"].astype(np.int64))
            self.recording_id = torch.from_numpy(data["recording_id"].astype(np.int64))
            self.source_id = torch.from_numpy(data["source_id"].astype(np.int64))
            self.endpoint_tow = torch.from_numpy(data["endpoint_tow"].astype(np.float64))
        if include_device_ids is not None:
            selected = torch.zeros(len(self.device_id), dtype=torch.bool)
            for device_id in include_device_ids:
                selected |= self.device_id == device_id
            self.x = self.x[selected]
            self.y = self.y[selected]
            self.device_id = self.device_id[selected]
            self.recording_id = self.recording_id[selected]
            self.source_id = self.source_id[selected]
            self.endpoint_tow = self.endpoint_tow[selected]
        if self.x.ndim != 2 or len(self.x) != len(self.y):
            raise ValueError(f"Invalid device tensor shapes in {path}")

    def __len__(self) -> int:
        return len(self.y)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.x[index], self.y[index]


class EventMLP(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, dropout: float) -> None:
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), nn.GELU(), nn.Dropout(dropout), nn.Linear(hidden_dim, 2)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.layers(x)


def make_model(kind: str, input_dim: int, hidden_dim: int, dropout: float) -> nn.Module:
    return nn.Linear(input_dim, 2) if kind == "linear" else EventMLP(input_dim, hidden_dim, dropout)


def metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float | int]:
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return {
        "samples": int(len(y_true)), "negative_support": int((y_true == 0).sum()), "positive_support": int((y_true == 1).sum()),
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "far": float(fp / (fp + tn)) if fp + tn else 0.0,
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
    }


@torch.no_grad()
def probabilities(model: nn.Module, data: EventDataset, device: torch.device, batch_size: int) -> np.ndarray:
    model.eval()
    batches = [model(data.x[start:start + batch_size].to(device)).cpu() for start in range(0, len(data), batch_size)]
    return torch.cat(batches).softmax(dim=1)[:, 1].numpy() if batches else np.empty(0, dtype=np.float64)


def evaluate_probability(data: EventDataset, probability: np.ndarray, threshold: float, device_names: dict[int, str]) -> dict[str, Any]:
    if len(probability) != len(data):
        raise ValueError("Probability count differs from event windows")
    predicted = (probability >= threshold).astype(np.int64)
    labels = data.y.numpy()
    result: dict[str, Any] = {"alarm_threshold": threshold, "overall": metrics(labels, predicted)}
    by_device: dict[str, dict[str, float | int]] = {}
    device_ids = data.device_id.numpy()
    for device_id in np.unique(device_ids):
        selected = device_ids == device_id
        by_device[device_names.get(int(device_id), str(device_id))] = metrics(labels[selected], predicted[selected])
    result["by_device"] = by_device
    return result


def evaluate(model: nn.Module, data: EventDataset, device: torch.device, batch_size: int, device_names: dict[int, str]) -> dict[str, Any]:
    return evaluate_probability(data, probabilities(model, data, device, batch_size), 0.5, device_names)


def load_checkpoint_model(checkpoint_path: Path, device: torch.device, input_dim: int) -> tuple[dict[str, Any], nn.Module]:
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    required = {"model", "input_dim", "hidden_dim", "dropout", "state_dict"}
    if missing := required.difference(checkpoint):
        raise ValueError(f"Invalid checkpoint; missing {sorted(missing)}")
    if input_dim != int(checkpoint["input_dim"]):
        raise ValueError("Checkpoint and tensor feature dimensions differ")
    model = make_model(checkpoint["model"], int(checkpoint["input_dim"]), int(checkpoint["hidden_dim"]), float(checkpoint["dropout"])).to(device)
    model.load_state_dict(checkpoint["state_dict"])
    return checkpoint, model


def calibrate_checkpoint(args: argparse.Namespace, device_names: dict[int, str], device: torch.device, include_device_ids: set[int] | None) -> None:
    val = EventDataset(args.data_dir / "val.npz", include_device_ids)
    checkpoint, model = load_checkpoint_model(args.checkpoint, device, val.x.shape[1])
    probability = probabilities(model, val, device, args.batch_size)
    candidates = [evaluate_probability(val, probability, threshold, device_names) for threshold in args.thresholds]
    eligible = [candidate for candidate in candidates if candidate["overall"]["far"] <= args.max_val_far]
    if eligible:
        selected = max(eligible, key=lambda candidate: (candidate["overall"]["macro_f1"], candidate["overall"]["recall"], -candidate["overall"]["far"]))
    else:
        selected = min(candidates, key=lambda candidate: (candidate["overall"]["far"], -candidate["overall"]["macro_f1"]))
    checkpoint["alarm_threshold"] = float(selected["alarm_threshold"])
    checkpoint["calibration"] = {"split": "val", "max_val_far": args.max_val_far, "metrics": selected}
    args.output_dir.mkdir(parents=True, exist_ok=True)
    calibrated_path = args.output_dir / f"calibrated_{args.checkpoint.name}"
    torch.save(checkpoint, calibrated_path)
    save_json(args.output_dir / "val_threshold_calibration.json", {"max_val_far": args.max_val_far, "selected": selected, "candidates": candidates})
    print(json.dumps({"checkpoint": str(calibrated_path), "selected_threshold": selected["alarm_threshold"], "val_metrics": selected["overall"]}, indent=2))


def class_weights(data: EventDataset) -> torch.Tensor:
    counts = torch.bincount(data.y, minlength=2).float()
    if torch.any(counts == 0):
        raise ValueError(f"Train split lacks an event class: {counts.tolist()}")
    return counts.sum() / (2.0 * counts)


def save_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2), encoding="utf-8")


def main() -> None:
    args = parse_args()
    seed_all(args.seed)
    metadata = json.loads((args.data_dir / "metadata.json").read_text(encoding="utf-8"))
    device_names = {int(value): str(key) for key, value in metadata.get("device_mapping", {}).items()}
    named_device_ids = {name: device_id for device_id, name in device_names.items()}
    include_device_ids: set[int] | None = None
    if args.include_devices:
        unknown = sorted(set(args.include_devices).difference(named_device_ids))
        if unknown:
            raise ValueError(f"Unknown device names: {unknown}; available={sorted(named_device_ids)}")
        include_device_ids = {named_device_ids[name] for name in args.include_devices}
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if args.test_only:
        test = EventDataset(args.data_dir / "test.npz", include_device_ids)
        checkpoint, model = load_checkpoint_model(args.checkpoint, device, test.x.shape[1])
        args.output_dir.mkdir(parents=True, exist_ok=True)
        threshold = float(checkpoint.get("alarm_threshold", 0.5))
        save_json(args.output_dir / "test_metrics_device_event.json", evaluate_probability(test, probabilities(model, test, device, args.batch_size), threshold, device_names))
        return
    if args.calibrate_only:
        calibrate_checkpoint(args, device_names, device, include_device_ids)
        return

    train = EventDataset(args.data_dir / "train.npz", include_device_ids)
    val = EventDataset(args.data_dir / "val.npz", include_device_ids)
    if len(val) == 0:
        raise ValueError("Validation is empty; use a tensor directory with an inner validation split")
    model = make_model(args.model, train.x.shape[1], args.hidden_dim, args.dropout).to(device)
    if args.dry_run:
        print(json.dumps({"device": str(device), "model": args.model, "train_windows": len(train), "val_windows": len(val), "features": int(train.x.shape[1])}))
        return
    criterion = nn.CrossEntropyLoss(weight=class_weights(train).to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    loader = DataLoader(train, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers)
    best_score, best_state, stale = float("-inf"), None, 0
    history: list[dict[str, float | int]] = []
    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        for x, y in loader:
            loss = criterion(model(x.to(device)), y.to(device))
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += float(loss.item()) * len(y)
        val_metrics = evaluate(model, val, device, args.batch_size, device_names)["overall"]
        row = {"epoch": epoch, "train_loss": total_loss / len(train), **val_metrics}
        history.append(row)
        score = float(val_metrics["macro_f1"])
        if score > best_score:
            best_score = score
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            stale = 0
        else:
            stale += 1
            if stale >= args.patience:
                break
    if best_state is None:
        raise RuntimeError("No checkpoint selected")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_path = args.output_dir / f"best_device_event_{args.model}.pt"
    torch.save({
        "model": args.model, "input_dim": int(train.x.shape[1]), "hidden_dim": args.hidden_dim, "dropout": args.dropout,
        "best_val_macro_f1": best_score, "state_dict": best_state, "task": "device_attack_event",
        "label_semantics": metadata["label_semantics"], "included_device_names": args.include_devices,
    }, checkpoint_path)
    save_json(args.output_dir / "training_history.json", history)
    model.load_state_dict(best_state)
    save_json(args.output_dir / "val_metrics_device_event.json", evaluate(model, val, device, args.batch_size, device_names))
    print(json.dumps({"checkpoint": str(checkpoint_path), "best_val_macro_f1": best_score, "epochs": len(history)}, indent=2))


if __name__ == "__main__":
    main()
