#!/usr/bin/env python3
"""Append predicted scene context to device-response tensors.

This is an exploratory conditional-fusion bridge.  For each split it loads a
trained band-scene checkpoint, predicts the four scene posteriors, aligns them
to device-response windows by ``recording_id + device_id + endpoint_tow``, and
appends five context features:

* ``scene_prob_normal``
* ``scene_prob_L1``
* ``scene_prob_L5``
* ``scene_prob_L1+L5``
* ``scene_context_available``

The original device labels and trace fields are copied unchanged.  The output
can be consumed directly by ``37_train_device_attack_event.py``.  Training
split context is generated by the same fold checkpoint and is therefore an
initial experiment, not yet a strict cross-fitted final result.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
from torch import nn

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(ROOT))

from models import BandMeanWindowClassifier


SCENE_NAMES = ("normal", "L1", "L5", "L1+L5")
CONTEXT_NAMES = tuple(f"scene_prob_{name}" for name in SCENE_NAMES) + ("scene_context_available",)
REQUIRED_RESPONSE = {"x", "recording_id", "device_id", "endpoint_tow"}
REQUIRED_SCENE = {"x", "recording_id", "device_id", "endpoint_tow", "single_band_mask"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--response-data-dir", type=Path, required=True)
    parser.add_argument("--scene-data-dir", type=Path, required=True)
    parser.add_argument("--scene-checkpoint", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--tow-decimals", type=int, default=3)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    if args.batch_size <= 0:
        parser.error("--batch-size must be positive")
    if not 0 <= args.tow_decimals <= 9:
        parser.error("--tow-decimals must be in [0, 9]")
    return args


def load_feature_names(path: Path) -> list[str]:
    names = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(names, list) or not all(isinstance(name, str) for name in names):
        raise ValueError(f"{path} must contain a JSON list of feature names")
    return names


def load_scene_model(checkpoint_path: Path, scene_feature_names: list[str], time_steps: int) -> tuple[nn.Module, list[int], dict]:
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    requested_names = checkpoint.get("feature_names") or scene_feature_names
    missing = sorted(set(requested_names).difference(scene_feature_names))
    if missing:
        raise ValueError(f"Scene checkpoint features missing from tensor: {missing}")
    indices = [scene_feature_names.index(name) for name in requested_names]
    model = BandMeanWindowClassifier(
        input_dim=len(indices),
        time_steps=time_steps,
        encoder=str(checkpoint["encoder"]),
        hidden_dim=int(checkpoint["hidden_dim"]),
        dropout=float(checkpoint["dropout"]),
        num_classes=int(checkpoint.get("num_classes", 4)),
    )
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()
    return model, indices, checkpoint


@torch.no_grad()
def predict_scene_probabilities(model: nn.Module, x: np.ndarray, batch_size: int, device: torch.device) -> np.ndarray:
    tensor = torch.from_numpy(x.astype(np.float32, copy=False))
    rows: list[np.ndarray] = []
    model.to(device)
    for start in range(0, len(tensor), batch_size):
        logits = model(tensor[start:start + batch_size].to(device))
        rows.append(torch.softmax(logits, dim=1).cpu().numpy())
    return np.concatenate(rows, axis=0) if rows else np.empty((0, 4), dtype=np.float32)


def make_key(recording_id: int, device_id: int, tow: float, decimals: int) -> tuple[int, int, float]:
    return int(recording_id), int(device_id), round(float(tow), decimals)


def build_context_map(scene_data: dict[str, np.ndarray], scene_prob: np.ndarray, decimals: int) -> dict[tuple[int, int, float], np.ndarray]:
    single_band = scene_data["single_band_mask"].astype(bool)
    context: dict[tuple[int, int, float], np.ndarray] = {}
    for index in range(len(scene_prob)):
        key = make_key(
            scene_data["recording_id"][index],
            scene_data["device_id"][index],
            scene_data["endpoint_tow"][index],
            decimals,
        )
        if key in context:
            raise ValueError(f"Duplicate scene endpoint key: {key}")
        values = np.zeros(5, dtype=np.float32)
        if not single_band[index]:
            values[:4] = scene_prob[index].astype(np.float32)
            values[4] = 1.0
        context[key] = values
    return context


def augment_split(
    response_path: Path,
    scene_path: Path,
    output_path: Path,
    model: nn.Module,
    scene_indices: list[int],
    batch_size: int,
    decimals: int,
    device: torch.device,
) -> tuple[int, int, int]:
    with np.load(response_path, allow_pickle=False) as response_npz:
        response_data = {name: np.asarray(response_npz[name]) for name in response_npz.files}
    with np.load(scene_path, allow_pickle=False) as scene_npz:
        scene_data = {name: np.asarray(scene_npz[name]) for name in scene_npz.files}
    missing_response = sorted(REQUIRED_RESPONSE.difference(response_data))
    missing_scene = sorted(REQUIRED_SCENE.difference(scene_data))
    if missing_response:
        raise ValueError(f"{response_path} is missing {missing_response}")
    if missing_scene:
        raise ValueError(f"{scene_path} is missing {missing_scene}")
    scene_x = scene_data["x"].astype(np.float32, copy=False)[:, :, scene_indices]
    scene_prob = predict_scene_probabilities(model, scene_x, batch_size, device)
    context_map = build_context_map(scene_data, scene_prob, decimals)
    response_x = response_data["x"].astype(np.float32, copy=False)
    context = np.zeros((len(response_x), 5), dtype=np.float32)
    matched = 0
    available = 0
    for index in range(len(response_x)):
        key = make_key(
            response_data["recording_id"][index],
            response_data["device_id"][index],
            response_data["endpoint_tow"][index],
            decimals,
        )
        values = context_map.get(key)
        if values is not None:
            matched += 1
            context[index] = values
            available += int(values[4] > 0.5)
    response_data["x"] = np.concatenate([response_x, context], axis=1)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(output_path, **response_data)
    return len(response_x), matched, available


def main() -> None:
    args = parse_args()
    if args.output_dir.exists() and any(args.output_dir.iterdir()) and not args.overwrite:
        raise FileExistsError(f"Output directory is not empty: {args.output_dir}; use --overwrite")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    response_names = load_feature_names(args.response_data_dir / "feature_names.json")
    scene_names = load_feature_names(args.scene_data_dir / "feature_names.json")
    scene_train = np.load(args.scene_data_dir / "train.npz", allow_pickle=False)
    scene_time_steps = int(scene_train["x"].shape[1])
    scene_train.close()
    model, scene_indices, checkpoint = load_scene_model(args.scene_checkpoint, scene_names, scene_time_steps)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    stats: dict[str, dict[str, int]] = {}
    for split in ("train", "val", "test"):
        response_path = args.response_data_dir / f"{split}.npz"
        scene_path = args.scene_data_dir / f"{split}.npz"
        output_path = args.output_dir / f"{split}.npz"
        rows, matched, available = augment_split(
            response_path, scene_path, output_path, model, scene_indices,
            args.batch_size, args.tow_decimals, device,
        )
        stats[split] = {"windows": rows, "scene_key_matched": matched, "scene_context_available": available}
        print(f"{split}: windows={rows} matched={matched} context_available={available}")
    metadata = json.loads((args.response_data_dir / "metadata.json").read_text(encoding="utf-8"))
    metadata["feature_names"] = response_names + list(CONTEXT_NAMES)
    metadata["conditioned_scene_context"] = {
        "source": str(args.scene_checkpoint),
        "scene_feature_names": [scene_names[index] for index in scene_indices],
        "context_feature_names": list(CONTEXT_NAMES),
        "alignment": "recording_id + device_id + endpoint_tow rounded to tow_decimals",
        "single_band_context": "zero posterior plus scene_context_available=0",
        "train_context_warning": "train probabilities are generated by the same fold checkpoint; use cross-fitted context for final reporting",
        "tow_decimals": args.tow_decimals,
    }
    metadata["conditioned_split_stats"] = stats
    (args.output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    (args.output_dir / "feature_names.json").write_text(
        json.dumps(response_names + list(CONTEXT_NAMES), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps({"output_dir": str(args.output_dir), "features": len(response_names) + len(CONTEXT_NAMES), "stats": stats}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
